### ISSUE TITLE
Lambda package doesn't compile after AWS SDK C++ update

### ISSUE THREAD

**Issue by NatxoM** [awslabs/aws-lambda-cpp#64] opened 2019-11-13 08:55 UTC
I'm following the instructions for creating a lambda package using  _AWS SDK C++_ and _S3_ from:

https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/

My _OS_ is `Docker FROM ubuntu:18.04`, and my _C++ SDK_ version is 1.7.224.

With a previous _C++ SDK_ version (1.7.210), It worked flawlessly. Now, I get:

```
[100%] Linking CXX executable XXX
/usr/bin/ld: cannot find -laws-c-event-stream
/usr/bin/ld: cannot find -laws-checksums
/usr/bin/ld: cannot find -laws-c-common
collect2: error: ld returned 1 exit status
make[2]: *** [XXX] Error 1
CMakeFiles/XXX.dir/build.make:140: recipe for target 'XXX' failed

```
Why? Should I change any _cmake_ instructions, which haven't been updated in the link above?

**Update**: the problem appears with 1.7.212

**Comment by marcomagdy** [comment] 2019-11-14 18:11
Thanks for reporting this.
I'm trying to reproduce the issue and will be communicating with the SDK team.
Either I'll need to update the blog post or something got broken in the SDK.

**Comment by marcomagdy** [comment] 2019-12-05 23:55
Looks like the issue has been resolved. Closing this one.

**Closed by marcomagdy** 2019-12-05 23:55 UTC
