### ISSUE TITLE
test the lambda locally

### ISSUE THREAD

**Issue by boulabiar** [awslabs/aws-lambda-cpp#59] opened 2019-08-28 21:10 UTC
Sorry for writing this as an issue.

What's the best way to test the lambda locally ?
There are no materials on the internet for testing custom run-time like C++.

**Comment by awood45** [comment] 2019-08-29 20:35
The https://github.com/awslabs/aws-sam-cli `sam local` functionality should work for C++ and other BYOL runtimes. You will have to ensure that you've built your function code, and that you're including the C++ runtime layer in your template, but it should work.

If you have any issues, feel free to open an issue in the https://github.com/awslabs/aws-sam-cli repo.

**Comment by marcomagdy** [comment] 2019-08-29 20:47
Getting Started with SAM CLI

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started.html

**Comment by marcomagdy** [comment] 2019-08-30 03:50
reopening this because I'm running into errors myself.

**Comment by marcomagdy** [comment] 2019-08-30 04:53
It looks like the issue is that sam cli messes up symlinks in the zip files ( https://github.com/awslabs/aws-sam-cli/issues/878).

You can try to build your C++ Lambda on Amazon Linux and tell CMake not to package libc (via `aws_lambda_package_target(${PROJECT_NAME} NO_LIBC)`) then the zip file will not have symlinks to system libraries. Obviously, if the Lambda still has symlinks to the application dependencies then the problem will not go away.

**Comment by marcomagdy** [comment] 2019-09-03 16:41
Closing this because the root cause is in SAM CLI issue referenced above.

**Closed by marcomagdy** 2019-09-03 16:41 UTC
